# Generated by Django 5.1.5 on 2025-04-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_transaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_consumed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                    ("Withdrawal", "Withdrawal"),
                ],
                max_length=15,
            ),
        ),
    ]
