# Generated by Django 5.1.5 on 2025-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_transaction_is_consumed_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_mode",
            field=models.CharField(default="Online", max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_consumed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                    ("Withdraw", "Withdraw"),
                ],
                max_length=10,
            ),
        ),
    ]
