# Generated by Django 5.1.5 on 2025-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_transaction_payment_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_consumed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_mode",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                    ("Withdrawal", "Withdrawal"),
                ],
                max_length=20,
            ),
        ),
    ]
