# Generated by Django 5.1.5 on 2025-04-10 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_transaction_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("is_essential", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_fund_target",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="savings_goal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="savings_goal_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurring_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Yearly", "Yearly"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Card", "Card"),
                    ("Online", "Online"),
                    ("UPI", "UPI"),
                    ("Bank Transfer", "Bank Transfer"),
                ],
                default="Online",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                    ("Withdrawal", "Withdrawal"),
                    ("Investment", "Investment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "date"], name="core_transa_user_id_190a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["type"], name="core_transa_type_3fe3dc_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category"], name="core_transa_categor_8fbb1e_idx"
            ),
        ),
    ]
